namespace: flux-system
tls:
  secretName: ""
  certContentField: ""
  keyContentField: ""
  localCertFile: "localhost.pem"
  localKeyFile: "localhost-key.pem"
wegoServerLogLevel: info
adminUsername: YWRtaW4=
adminPassword:
