# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-vet
      exclude: '^tools'
    - id: golangci-lint
      args:
        - --skip-files=tilt_modules
        - --out-format=github-actions
        - --timeout=600s

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.9.0
  hooks:
    - id: eslint
      files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
      types: [file]
      # exclude uses a regex https://pre-commit.com/index.html#regular-expressions
      exclude: "^(bin|dist|node_modules|tilt_modules)/"
      additional_dependencies:
        - "@typescript-eslint/eslint-plugin@4.16.1"
        - "@typescript-eslint/parser@4.16.1"
        - "eslint-plugin-import@2.22.1"
        - "eslint@7.28.0"
