apiVersion: templates.weave.works/v1alpha2
kind: GitOpsTemplate
metadata:
  name: aws-eks-dev
  namespace: default
  annotations:
    templates.weave.works/inject-prune-annotation: "true"
    templates.weave.works/add-common-bases: "true"
  labels:
    weave.works/template-type: cluster
spec:
  description: AWS EKS Development Cluster
  params:
    - name: CLUSTER_NAME
      description: The name for this cluster.
    - name: AWS_REGION
      description: AWS Region to create cluster
      options: ["us-east-1", "eu-central-1", "eu-west-2", "us-west-2"]
    - name: KUBERNETES_VERSION
      description: EKS Kubernetes version to use
      options: ["v1.19.8", "v1.20.7", "v1.21.2"]
    - name: WORKER_MACHINE_COUNT
      description: Number of worker nodes to create.
  charts:
    helmRepositoryTemplate:
      path: ${NAMESPACE}/${CLUSTER_NAME}/helm-repo.yaml
    items:
      - chart: cert-manager
        targetNamespace: cert-manager
        editable: true
        version: 0.0.8
        template:
          path: ${NAMESPACE}/${CLUSTER_NAME}/cert-manager.yaml
          content:
            spec:
              install:
                remediation:
                  retries: 3
  resourcetemplates:
    - path: ./clusters/management/clusters/${CLUSTER_NAME}.yaml
      contents:
        - apiVersion: gitops.weave.works/v1alpha1
          kind: GitopsCluster
          metadata:
            name: "${CLUSTER_NAME}"
            namespace: default
            labels:
              weave.works/capi: bootstrap
          spec:
            capiClusterRef:
              name: "${CLUSTER_NAME}"

        - apiVersion: cluster.x-k8s.io/v1beta1
          kind: Cluster
          metadata:
            name: ${CLUSTER_NAME}
            namespace: default
            labels:
              weave.works/capi: bootstrap
          spec:
            clusterNetwork:
              pods:
                cidrBlocks:
                  - 192.168.0.0/16
            controlPlaneRef:
              apiVersion: controlplane.cluster.x-k8s.io/v1beta1
              kind: AWSManagedControlPlane
              name: ${CLUSTER_NAME}-control-plane
            infrastructureRef:
              apiVersion: controlplane.cluster.x-k8s.io/v1beta1
              kind: AWSManagedControlPlane
              name: ${CLUSTER_NAME}-control-plane

        - apiVersion: controlplane.cluster.x-k8s.io/v1beta1
          kind: AWSManagedControlPlane
          metadata:
            name: ${CLUSTER_NAME}-control-plane
            namespace: default
          spec:
            region: ${AWS_REGION}
            sshKeyName: default
            version: ${KUBERNETES_VERSION}
            eksClusterName: ${CLUSTER_NAME}

        - apiVersion: cluster.x-k8s.io/v1beta1
          kind: MachinePool
          metadata:
            name: ${CLUSTER_NAME}-pool-0
            namespace: default
          spec:
            clusterName: ${CLUSTER_NAME}
            replicas: ${WORKER_MACHINE_COUNT}
            template:
              spec:
                bootstrap:
                  dataSecretName: ""
                clusterName: ${CLUSTER_NAME}
                infrastructureRef:
                  apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
                  kind: AWSManagedMachinePool
                  name: ${CLUSTER_NAME}-pool-0

        - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: AWSManagedMachinePool
          metadata:
            name: ${CLUSTER_NAME}-pool-0
            namespace: default
          spec: {}
