apiVersion: v1
kind: Namespace
metadata:
  name: team-a
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: limited-user
  namespace: team-a
  labels:
    gitops.weave.works/entity: user
data:
  username: {{ "limited" | b64enc | quote }}
  # password = limited
  password: {{ "$2a$10$leQSwKxbUhSDb9YRS3UwEeXPBb18jTGuyKnwmtVcxwYlyfsnwGsem" | b64enc | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: limited-user-role
  namespace: team-a
rules:
  - apiGroups: ["apps"]
    resources: [ "deployments", "replicasets", "pods" ]
    verbs: [ "get", "list" ]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: [ "kustomizations" ]
    verbs: [ "get", "list" ]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: [ "helmreleases" ]
    verbs: [ "get", "list" ]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories" ]
    verbs: [ "get", "list" ]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: limited-user-read-resources
  namespace: team-a
subjects:
  - kind: User
    name: dev
    namespace: team-a
roleRef:
  kind: Role
  name: limited-user-role
  apiGroup: rbac.authorization.k8s.io
---
