apiVersion: apps/v1
kind: Deployment
metadata:
  name: wego-app
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wego-app
    spec:
      serviceAccountName: wego-app-service-account
      containers:
        - name: wego-app
          image: {{ .Values.images.wegoApp }}
          args: ["ui", "run", "-l", "--helm-repo-namespace", "{{.Release.Namespace}}"]
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: IfNotPresent
  selector:
    matchLabels:
      app: wego-app
