apiVersion: apps/v1
kind: Deployment
metadata:
  name: wego-app
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wego-app
      {{- if and .Values.tls.localCertFile .Values.tls.localKeyFile }}
      annotations:
        tls-cert: {{.Files.Get .Values.tls.localCertFile | quote }}
        tls-key: {{.Files.Get .Values.tls.localKeyFile | quote }}
      {{ end }}
    spec:
      serviceAccountName: wego-app-service-account
      containers:
        - name: wego-app
          image: "{{.Values.containerRegistry}}:{{.Values.image}}"
          args: [ "--log-level", "{{.Values.wegoServerLogLevel}}", "--helm-repo-namespace", "{{.Values.namespace}}","--tls-cert-file","/etc/tls-volume/.cert-file","--tls-private-key-file","/etc/tls-volume/.key-file" ]
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: IfNotPresent
          env:
          - name: WEAVE_GITOPS_AUTH_ENABLED
            value: "true"
          volumeMounts:
            - name: tls-volume
              readOnly: true
              mountPath: "/etc/tls-volume"
      {{ if .Values.tls.secretName}}
      volumes:
        - name: tls-volume
          secret:
            secretName: {{ .Values.tls.secretName }} # This needs to be a parameter
      {{- else -}}
      volumes:
        - name: tls-volume
          downwardAPI:
            items:
              - path: ".cert-file"
                fieldRef:
                  fieldPath: metadata.annotations['tls-cert']
              - path: ".key-file"
                fieldRef:
                  fieldPath: metadata.annotations['tls-key']
      {{- end }}
  selector:
    matchLabels:
      app: wego-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: weave-gitops-binding
subjects:
  - kind: ServiceAccount
    name: wego-app-service-account
    namespace: {{.Values.namespace}}
roleRef:
  kind: ClusterRole
  name: weave-gitops-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-watcher-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-watcher-role
subjects:
  - kind: ServiceAccount
    name: wego-app-service-account
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weave-gitops-role
rules:
  - apiGroups: [""]
    resources: [ "users", "groups", "serviceaccounts" ]
    verbs: [ "impersonate" ]
  - apiGroups: [""]
    resources: [ "secrets" ]
    verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-watcher-role
rules:
  - apiGroups: [ "source.toolkit.fluxcd.io" ]
    resources: [ "helmrepositories" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "source.toolkit.fluxcd.io" ]
    resources: [ "helmrepositories/finalizers", "helmrepositories/status" ]
    verbs: [ "get" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wego-app-service-account
  namespace: {{.Values.namespace}}
secrets:
  - name: wego-app-service-account-token
---
apiVersion: v1
kind: Service
metadata:
  name: wego-app
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: wego-app
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
