{{- if (and .Values.adminUser.create .Values.adminUser.createSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.adminUserSecret" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- with .Values.adminUser }}
  username: {{ .username | b64enc | quote }}
  password: {{ .passwordHash | required "passwordHash must be set!" | b64enc | quote }}
  {{- end }}
{{- end }}
