apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--log-level"
            - "{{ .Values.logLevel }}"
            {{- if .Values.serverTLS.enable }}
            - "--tls-cert-file"
            - {{ .Values.TLSCertFile }}
            - "--tls-private-key-file"
            - {{ .Values.TLSKeyFile }}
            {{- else }}
            - "--insecure"
            {{- end }}
          {{- with .Values.additionalArgs }}
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if or .Values.enableLogin .Values.envVars}}
          env:
            - name: PROFILE_CACHE_LOCATION
              value: {{ .Values.profileCacheLocation }}
            - name: NOTIFICATION_CONTROLLER_ADDRESS
              value: {{ .Values.notificationControllerAddress }}
            - name: WATCHER_PORT
              value: {{ .Values.watcherPort }}
            - name: OIDC_ISSUER_URL
              value: {{ .Values.OIDCIssuerURL }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.OIDCClientID }}
            - name: OIDC_CLIENT_SECRET
              value: {{ .Values.OIDCClientSecret }}
            - name: OIDC_REDIRECT_URL
              value: {{ .Values.OIDCRedirectURL }}
            - name: OIDC_TOKEN_DURATION
              value: {{ .Values.OIDCTokenDuration }}
            - name: DEV_MODE
              value: {{ .Values.DEV_MODE }}
            - name: DEV_USER
              value: {{ .Values.DEV_USER }}
          {{- if .Values.enableLogin }}
            - name: WEAVE_GITOPS_AUTH_ENABLED
              value: "true"
          {{- end }}
          {{- with .Values.envVars }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.serverTLS.enable }}
          volumeMounts:
            - name: tls-volume
              readOnly: true
              mountPath: "/etc/tls-volume"
          {{- end }}
      {{- if .Values.serverTLS.enable }}
      volumes:
        - name: tls-volume
          secret:
            secretName: {{ .Values.serverTLS.secretName }}
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
