apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wego-admin-gitops-apps-reader
  namespace: flux-system
subjects:
  - kind: User
    name: wego-admin
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: gitops-apps-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wego-admin-gitops-templates-reader
  namespace: default
subjects:
  - kind: User
    name: wego-admin
    namespace: default
roleRef:
  kind: ClusterRole
  name: gitops-templates-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wego-admin-gitops-secrets-reader
  namespace: default
subjects:
  - kind: User
    name: wego-admin
    namespace: default
roleRef:
  kind: ClusterRole
  name: gitops-secrets-reader
  apiGroup: rbac.authorization.k8s.io

