on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: publish
jobs:
  publish-s3-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: go build -o wego
    - name: publish
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: |
        aws s3 cp wego s3://weave-gitops/wego
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Packages Docker Registry
        run: docker login -u ${{ secrets.DOCKER_HUB_PASSWORD }} -p ${{ secrets.DOCKER_HUB_PASSWORD }} docker.io
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag weaveworks/weave-gitops:${{ github.sha }}
      - name: Push the latest Docker image
        run: docker push weaveworks/weave-gitops:${{ github.sha }}