name: Docs

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'website/**'
  push:
    branches:
      - 'main'
    paths:
      - 'website/**'

jobs:
  update-doc-repo-files:
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Create GitOps binary
        run: |
          make all
      - name: Set up environment vars
        run: |
          echo "BRANCH=release-doc-updates-$$" >> $GITHUB_ENV
          echo "GITOPS_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Update with new version
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          GA_KEY: "dummy"
        run: |
          bash tools/update-docs.sh ${PWD}/bin/gitops ${PWD}/website
      - name: Git diff
        run: |
          git diff
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@9825ae65b1cb54b543b938503728b432a0176d29 # v3
      #   with:
      #     token: ${{ secrets.WEAVE_GITOPS_DOCS_WEAVEWORKS_DOCS_BOT_PAT }}
      #     committer: GitHub <noreply@github.com>
      #     author: weave-test-user <weave-test-user@example.com>
      #     signoff: true
      #     # path: doc-repo
      #     branch: ${{ env.BRANCH }}
      #     title: "Documentation updates for ${{ env.GITOPS_VERSION }}"
      #     body: "Update version references to ${{ env.GITOPS_VERSION }} and create new versioned documentation set."
  staging-release:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
      - uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
        with:
          node-version: "14.x"
      - name: Test Build
        env:
          GA_KEY: "dummy"
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.PROD_DOCS_GITOPS_UPLOAD }}
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: website/build
          destination: staging.docs.gitops.weave.works
          parent: false
  prod-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
      - uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
        with:
          node-version: "14.x"
      - uses: weaveworks/webfactory-ssh-agent@6b2f2c5354ff41f1edbbf7a17ea9b6178c89be9f
        with:
          ssh-private-key: ${{ secrets.WEAVE_GITOPS_DOCS_WEAVEWORKS_DOCS_BOT_DEPLOY_KEY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          GA_KEY: ${{ secrets.GA_KEY }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          git config --global user.email "corporate-it+weaveworks-docs-bot@weave.works"
          git config --global user.name "weaveworks-docs-bot"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.PROD_DOCS_GITOPS_UPLOAD }}
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: website/build
          destination: production.docs.gitops.weave.works
          parent: false
