on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CI_CONTAINER_REGISTRY: europe-west1-docker.pkg.dev
  CI_CONTAINER_REPOSITORY: europe-west1-docker.pkg.dev/weave-gitops-clusters/weave-gitops

name: PR CI Workflow
jobs:

  ci-static:
    name: CI Check Static Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20.X]
        node-version: [16.X]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - run: make check-format

  finish-ci-pr:
    name: PR CI Pipeline
    runs-on: ubuntu-latest
    needs:
      - ci-static
    if: github.event_name != 'push'
    steps:
      - run: echo "All done"