name: release

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: weaveworks/wego-app

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
          git fetch --tags -f
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Set env var
        run: |
          make -B dependencies
          echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "FLUX_VERSION=$($(pwd)/tools/bin/stoml $(pwd)/tools/dependencies.toml flux.version)" >> $GITHUB_ENV
          echo "GORELEASER_PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))" >> $GITHUB_ENV
          echo "GORELEASER_CURRENT_TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: "Make All"
        run: make all
      - name: "Git diff"
        run: git --no-pager diff
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: "${{ github.workspace }}/.github/changelog/changelog_configuration.json"
          outputFile: "${{ runner.temp }}/changelog.md"
          ignorePreReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --release-notes=${{ runner.temp }}/changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ env.BRANCH }}
          FLUX_VERSION: ${{ env.FLUX_VERSION }}
          GORELEASER_PREVIOUS_TAG: ${{ env.GORELEASER_PREVIOUS_TAG }}
          GORELEASER_CURRENT_TAG:  ${{ env.GORELEASER_CURRENT_TAG }}
  publish_npm_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"
          registry-url: "https://npm.pkg.github.com"
          scope: "@weaveworks"
      - run: npm install
      - run: make ui-lib && cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
          flavor: |
            latest=true
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  update-doc-repo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout WG
        uses: actions/checkout@v2
        with:
          path: main-repo
      - name: Checkout Docs
        uses: actions/checkout@v2
        with:
          repository: weaveworks/weave-gitops-docs
          path: doc-repo
          token: ${{ secrets.WEAVE_GITOPS_DOCS_WEAVEWORKS_DOCS_BOT_DEPLOY_KEY }}
      - name: Unshallow
        run: |
          cd main-repo
          git fetch --prune --unshallow
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Create GitOps binary
        run: |
          cd main-repo
          make all
      - name: Set up environment vars
        run: |
          echo "BRANCH=release-doc-updates-$$" >> $GITHUB_ENV
          cd main-repo
          echo "GITOPS_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Update with new version
        env:
          GITOPS_VERSION: ${{ env.GITOPS_VERSION }}
          ALGOLIA_API_KEY ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          cd doc-repo/docs
          yarn install
          # update version information
          ex - installation.md << EOS
          /download\/
          %s,download/\(.*\)/,download/$GITOPS_VERSION/,
          /Current Version
          .,+4! ../../main-repo/bin/gitops version
          +5d
          wq!
          EOS
          # create CLI reference
          ../../main-repo/bin/gitops docs
          git add *.md
          git rm -f --ignore-unmatch cli-reference.md
          ex - gitops.md << EOS
          1i
          ---
          sidebar_position: 3
          ---

          # CLI Reference

          .
          wq!
          # create versioned docs
          cd ..
          version_number=$(cut -f2 -d'v' <<< $GITOPS_VERSION)
          npm run docusaurus docs:version $version_number
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@9825ae65b1cb54b543b938503728b432a0176d29 # v3
        with:
          token: ${{ secrets.WEAVE_GITOPS_DOCS_WEAVEWORKS_DOCS_BOT_DEPLOY_KEY }}
          committer: GitHub <noreply@github.com>
          author: weave-test-user <weave-test-user@example.com>
          signoff: true
          path: doc-repo
          branch: ${{ env.BRANCH }}
          title: "Documentation updates for ${{ env.GITOPS_VERSION }}"
          body: "Updated version references to ${{ env.GITOPS_VERSION }} and create new versioned documentation set."
